### ISSUE TITLE
Parts unresponsive in KSP 1.1.0

### ISSUE THREAD

**Issue by SmartSouth** [NathanKell/ProceduralWings#9]
Once a procedural wing is attached to the fuselage, it becomes completely unresponsive to the g/m/t keys. Crafts made in the previous version (1.0.5) of KSP containing procedural parts lose their settings and are so unresponsive they cannot even be removed.

**Comment by NathanKell** [comment]
This repo is closed. Please see @Crzyrndm 's fork, CrzyRndm is the current maintainer.
